package org.tinywind.graphqlschemagenerator

/** A schema shaped like a small community site: enums, a self reference, a composite key and columns that need rules. */
object Fixtures {
    fun column(
        name: String,
        sqlType: String,
        userType: String? = null,
        isArray: Boolean = false,
        nullable: Boolean = false,
        primaryKey: Boolean = false,
        foreignKey: Boolean = false,
        comment: String? = null,
        precision: Int = 0,
        scale: Int = 0,
    ) = ColumnModel(name, sqlType, userType, isArray, nullable, primaryKey, foreignKey, comment, precision, scale)

    val boardType = EnumModel("board_type", listOf("NOTICE", "GENERAL", "COMMITTEE"), "Board categories.")
    val reviewStatus = EnumModel("review_status", listOf("PENDING", "APPROVED"), null)
    val draftType = EnumModel("draft_type", listOf("SIGNUP", "POST"), null)

    val committee = TableModel(
        "committee",
        "Standing committees.",
        listOf(
            column("id", "uuid", primaryKey = true),
            column("name", "character varying"),
            column("created_at", "timestamp with time zone"),
            column("budget", "numeric", nullable = true, precision = 14, scale = 0),
            column("share", "numeric", nullable = true, precision = 5, scale = 2),
        ),
    )

    val board = TableModel(
        "board",
        null,
        listOf(
            column("id", "uuid", primaryKey = true),
            column("name", "character varying"),
            column("board_type", "USER-DEFINED", userType = "board_type", comment = "NOTICE allows guest reading; \"quoted\" words stay."),
            column("cohort_number", "integer", nullable = true),
            column("committee_id", "uuid", nullable = true, foreignKey = true),
            column("active", "boolean"),
            column("display_order", "integer"),
            column("created_at", "timestamp with time zone"),
        ),
    )

    val user = TableModel(
        "user",
        null,
        listOf(
            column("id", "uuid", primaryKey = true),
            column("login_id", "character varying"),
            column("password_hash", "text"),
            column("tags", "text ARRAY", userType = "text", isArray = true, nullable = true),
            column("profile", "jsonb", nullable = true),
            column("view_count", "bigint"),
            column("birth_date", "date", nullable = true),
            column("referrer_id", "uuid", nullable = true, foreignKey = true),
        ),
    )

    val eventRsvp = TableModel(
        "event_rsvp",
        null,
        listOf(
            column("event_id", "uuid", primaryKey = true, foreignKey = true),
            column("user_id", "uuid", primaryKey = true, foreignKey = true),
            column("status", "USER-DEFINED", userType = "review_status"),
        ),
    )

    val feedMention = TableModel(
        "feed_mention",
        null,
        listOf(
            column("feed_id", "uuid", foreignKey = true),
            column("user_id", "uuid", foreignKey = true),
        ),
    )

    val schema = SchemaModel("public", listOf(boardType, reviewStatus, draftType), listOf(committee, board, user, eventRsvp, feedMention))

    fun configuration(configure: Generator.() -> Unit = {}): Configuration = Configuration().apply {
        generator {
            tables { include("board", "committee", "user", "event_rsvp") }
            columns { exclude("user.password_hash") }
            types { override("user.profile", "String") }
            configure()
        }
    }

    val expectedSdl: String = """
        # Generated by GRAPHQL-SCHEMA-GENERATOR from database schema "public". Do not edit.

        "Board categories."
        enum BoardType {
            NOTICE
            GENERAL
            COMMITTEE
        }

        enum ReviewStatus {
            PENDING
            APPROVED
        }

        type Board {
            id: UUID!
            name: String!
            ""${'"'}
            NOTICE allows guest reading; "quoted" words stay.
            ""${'"'}
            boardType: BoardType!
            cohortNumber: Int
            active: Boolean!
            displayOrder: Int!
            createdAt: DateTime!
        }

        "Standing committees."
        type Committee {
            id: UUID!
            name: String!
            createdAt: DateTime!
            budget: Long
            share: BigDecimal
        }

        type EventRsvp {
            eventId: UUID!
            userId: UUID!
            status: ReviewStatus!
        }

        type User {
            id: UUID!
            loginId: String!
            tags: [String!]
            profile: String
            viewCount: Long!
            birthDate: Date
        }

    """.trimIndent()
}
